baseURL = "https://blog.onyxframework.com/"
languageCode = "en-us"
title = "Onyx Framework Blog"
theme = "hugo-paper"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = false
enableRobotsTXT = true
canonifyURLs = true
googleAnalytics = "UA-135279567-2"

[menu]

  [[menu.main]]
    name = "Visit onyxframework.com"
    url = "https://onyxframework.com"
    weight = -110

  [[menu.main]]
    name = "See this blog on github.com"
    url = "https://github.com/onyxframework/blog"
    weight = -100

[params]
  description = "Read Onyx Framework development and community news, learn about its powers and how-to's."
  images = ["/images/twitter-card.png"]
